### ISSUE TITLE
Open Graph Image

### ISSUE THREAD

**Issue by birobirobiro** [brunocroh/bolhadev.chat#15]
The image is missing from Open Graph.

![image](https://github.com/brunocroh/bolhadev.chat/assets/22185823/9cc69839-82b3-482f-a5a0-b85f2e01c553)

https://opengraph.dev/panel?url=https%3A%2F%2Fbolhadev.chat%2F

**Comment by brunocroh** [comment]
![Screenshot 2024-06-02 at 08 35 28](https://github.com/brunocroh/bolhadev.chat/assets/13812512/e6cd9bed-fcfe-4c2d-b02a-1eb982c81aac)

New logo added as open graph cca91af112d04ea714a6e02382d2cb994eded1c6
