### ISSUE TITLE
Problem using size-full in tailwindcss

### ISSUE THREAD

**Issue by wendesongomes** [brunocroh/bolhadev.chat#21]
Because of tailwindcss/enforces-shorthand I can't use w-full and h-full, it changes to size-full.
![image](https://github.com/brunocroh/bolhadev.chat/assets/82889172/2ea6de23-25fe-430d-bd0f-bbe6a87e8882)

And in tailwindcss the size is not showing
![image](https://github.com/brunocroh/bolhadev.chat/assets/82889172/90cfdfeb-d314-4ecf-a88b-e074ec7b62cc)

**Comment by brunocroh** [comment]
So, I updated some eslint rules and project dependencies, could you check again if this works fine for you?

**Comment by wendesongomes** [comment]
Yes, it worked, thanks.

**Comment by brunocroh** [comment]
Nice, thank you
