### ISSUE TITLE
Improve deploy action to just run when have changes on server project

### ISSUE THREAD

**Issue by brunocroh** [brunocroh/bolhadev.chat#24]
Actually backend is deployed on each new commit, so will be good if we can improve it to just deploy when have changes on `apps/server/*`

**Comment by BIEMAX** [comment]
## Suggestion

You can disable direct commits to the main branch. Instead, create a secondary branch (e.g., named `dev`), so all PRs will first be merged into this new branch. After that, deploy to production.

All security checks can run in this branch too, avoiding duplicate checks in both branches (the main branch will be used only to deploy the application).

**Comment by brunocroh** [comment]
@BIEMAX Hey man, thank you for your Input.

I really do not like this approach of having a intermediate branch

Having this intermediate branch, is something more like Git Flow, and I really do no like it for web apps (The original author of git flow think the same, you can check the disclaimer on his [original article](https://nvie.com/posts/a-successful-git-branching-model/))

Other reason is because the basic principle of Continuous Delivery is "Software is always in releasable state", if you have interest on it, [this video](https://youtu.be/i2DrLsnETk4) will be awesome.

I believe that just will made us be more distant of our goal, ship fast.

Of course, even applying Git Flow, it would be good to have a ci/cd that does not perform unnecessary tasks to use fewer resources and be faster.

Any question or miss understanding of my side, let me know.
Thank you again for your time and idea.

**Comment by joaoreider** [comment]
Hi! I would like to work on this issue. Could you please assign it to me? @brunocroh

**Comment by brunocroh** [comment]
> Hi! I would like to work on this issue. Could you please assign it to me? @brunocroh

Yes sure, go ahead.
