### ISSUE TITLE
Put the github icon at the right corner of page with absolute.

### ISSUE THREAD

**Issue by brunocroh** [brunocroh/bolhadev.chat#31]
We changed the way the GitHub icon appears on the page, but it is inside the header container, the idea is to move it to the right corner of the page.

![Screenshot 2024-06-06 at 21 50 28](https://github.com/brunocroh/bolhadev.chat/assets/13812512/f4ea6b77-a4c1-4263-b317-1c8a0fbdccca)

**Comment by kawanofer** [comment]
working on it

**Comment by kawanofer** [comment]
https://github.com/brunocroh/bolhadev.chat/pull/32
