### ISSUE TITLE
Navigation bug on "Get Started" button click

### ISSUE THREAD

**Issue by LucasJantschChitolina** [brunocroh/bolhadev.chat#44]
When clicking on the "Get started" button, the app redirects to `/room/room/queue` since the href is a relative URL.

https://github.com/brunocroh/bolhadev.chat/assets/62803510/70fdd90b-b4cb-4446-bc6f-f84894c9d228

This is a simple fix, but I'm wondering if it wouldn't be better to hide the button on this screen, since I'm already on it

**Comment by brunocroh** [comment]
Thanks, for your feedback, fixed on commit [49258ce](https://github.com/brunocroh/bolhadev.chat/commit/49258ce1823f51b022d9a4178b39a2e9bcc3abb6)
