### ISSUE TITLE
Set Output Device

### ISSUE THREAD

**Issue by birobirobiro** [brunocroh/bolhadev.chat#5]
Create another option to select output device
![image](https://github.com/brunocroh/bolhadev.chat/assets/22185823/adfa91b0-d9c4-4ee7-9517-b018eae73a7c)

Like Google Meet example
![image](https://github.com/brunocroh/bolhadev.chat/assets/22185823/3805ef8b-ca90-408c-b7a6-6c7ea69ade8a)

**Comment by brunocroh** [comment]
Is the idea to change the way inputs are appearing? Or something else? I don't know if I understand it well, sorry.

**Comment by birobirobiro** [comment]
> Is the idea to change the way inputs are appearing? Or something else? I don't know if I understand it well, sorry.

That's right! Change the audio output device, as it can happen on Linux or Windows systems that even if the default device is selected, the sound will come out on another device. Therefore, it would be good to have another select option to change

**Comment by jacksonvieiracs** [comment]
I started this feature in a separate branch along with some specific changes to the styles of the select element. currently am refactoring some parts of my implementation to make the PR.

https://github.com/Jackson-Vieira/bolhadev.chat/tree/feature/set-output-device

**Comment by brunocroh** [comment]
So, on my side, I have all my devices listed.

![Screenshot 2024-05-30 at 10 07 17](https://github.com/brunocroh/bolhadev.chat/assets/13812512/a7de8079-ef54-4580-9c5f-2a3385567b20)

Is it not happening to you @birobirobiro ?

Could you give more details about OS, and browser?
What happens if you refresh the page and try again?

**Comment by birobirobiro** [comment]
> So, on my side, I have all my devices listed.
> 
> 
> 
> ![Screenshot 2024-05-30 at 10 07 17](https://github.com/brunocroh/bolhadev.chat/assets/13812512/a7de8079-ef54-4580-9c5f-2a3385567b20)
> 
> 
> 
> Is it not happening to you @birobirobiro ?
> 
> 
> 
> Could you give more details about OS, and browser?
> 
> What happens if you refresh the page and try again?
> 
> 

Yes, it appears! But this is the Input (microphones) I'm saying in relation to the Output (headphones, speakers). Have the option to also select the output device. It's not a bug, it's a feature.

**Comment by brunocroh** [comment]
Ah, I get it now, sorry.

If you need help, let me know @Jackson-Vieira
