### ISSUE TITLE
What values i should use in the environment variables?

### ISSUE THREAD

**Issue by jacksonvieiracs** [brunocroh/bolhadev.chat#6]
I'm a beginner with Next.js and following the contribution guide, when i run the project and enter in a queue or room, I received an error indicating that a specific environment variable is not specified and has set to undefined. 

![image](https://github.com/brunocroh/bolhadev.chat/assets/85802038/83a9c443-ba1a-4b99-ab8e-c62145fccc9d)

**Comment by brunocroh** [comment]
Oh, backend is running on port 4000

So the following .envs will works

```
NEXT_PUBLIC_SOCKET_URL=ws://localhost:4000
```
I will add it to docs and put a fallback when empty.

Thank you

**Comment by fabricionaweb** [comment]
Another suggestion would be to have .env.template filled with minimal values as example - instead of empty

**Comment by brunocroh** [comment]
Added default values to .env.template and mention it on contributing guide. https://github.com/brunocroh/bolhadev.chat/commit/6b03297d0d7340ae75e5ca949cdc162b93490b28
