### ISSUE TITLE
We need to add responsive layouts to works well on mobile devices.

### ISSUE THREAD

**Issue by brunocroh** [brunocroh/bolhadev.chat#7]

**Comment by renanr0cha** [comment]
Hello there! There's someone actively working on this issue, or can I do it? I saw some PRs mentioning fixes, but I plan to take a more comprehensive look at the pages. Also, I plan to look at larger resolutions, like QuadHD and 4K. What do you think? I would make separate PRs for the Mobile adjusts and the Above 1080p ones.

**Comment by brunocroh** [comment]
Nice Renan, for now we are adding it one piece per time, one screen that will be very important to work well on mobile is Room Screen, could you work on that?

The file I talking about is one bellow https://github.com/brunocroh/bolhadev.chat/blob/9f7277a6cf380a9360e4c1163c38c96e7ad39dd0/apps/web/app/room/%5Bslug%5D/page.tsx

**Comment by renanr0cha** [comment]
Nice. On it

**Comment by renanr0cha** [comment]
I'm trying to push the changes, but I'm getting a .env error:

![image](https://github.com/brunocroh/bolhadev.chat/assets/23660355/ac034204-d576-421a-966d-d35607deca88)

My .env looks like this:
```
NEXT_PUBLIC_SOCKET_URL=ws://localhost:4000
NEXT_SUPABASE_URL=
NEXT_SUPABASE_KEY=
```

**Comment by brunocroh** [comment]
> I'm trying to push the changes, but I'm getting a .env error:
> 
> ![image](https://private-user-images.githubusercontent.com/23660355/339407044-ac034204-d576-421a-966d-d35607deca88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTE5MzUsIm5iZiI6MTcxODI5MTYzNSwicGF0aCI6Ii8yMzY2MDM1NS8zMzk0MDcwNDQtYWMwMzQyMDQtZDU3Ni00MjFhLTk2NmQtZDM1NjA3ZGVjYTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE1MTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NjNjYmRjMmFiNzdiZjM5MTM2NzM4YzRkNmNjZjFhZDhiOWFiY2Y0NGM4M2YyM2RhMzBkMGYwMmRlZDVjODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o86V4Ra_WkiugQYoLif4ZlsV-FoTAUwvAhd4PC6JLlo)
> 
> My .env looks like this:
> 
> ```
> NEXT_PUBLIC_SOCKET_URL=ws://localhost:4000
> NEXT_SUPABASE_URL=
> NEXT_SUPABASE_KEY=
> ```

Oh sorry, my bad for it.

```
NEXT_PUBLIC_SOCKET_URL=ws://localhost:4000
NEXT_SUPABASE_URL=anything
NEXT_SUPABASE_KEY=just_to_run
```

Just add any values for these 2 envs and it will works fine.
